name: Rotina Incremental Omie ETL

on:
  schedule:
    # Roda de hora em hora (no minuto 0)
    - cron: '0 * * * *'
  workflow_dispatch: # Permite rodar manualmente clicando em um botão no Github

jobs:
  run-etl-incremental:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checando o código do repositório
        uses: actions/checkout@v3

      - name: Configurando o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalando dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Executando Script Incremental de Contas a Pagar
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python contas_pagar_incremental.py
